TS_SEARCH_PATHS=(
    "$HOME/Dropbox:3"
    "$HOME/Code:3"
    "$HOME/Courses:3"
    "$HOME/Documents:2"
    "$HOME/.config:2"
)

TS_SESSION_COMMANDS=(
    "nvim ."
    "lazygit"
)

TS_LOG_FILE="$HOME/.config/tmux/tmux-sessionizer/tmux-sessionizer.logs"
